[tool.pyright]

typeCheckingMode = "basic"
reportUnusedImport = "warning"
pythonVersion = 3.7
typeshedPath = "typeshed"
enableTypeIgnoreComments = true
reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportPrivateUsage = "warning"
reportUntypedFunctionDecorator = "none"
reportMissingTypeStubs = false
reportUnboundVariable = "warning"
reportMissingImports = "warning"
reportGeneralTypeIssues = "none"

verboseOutput = true
