[tool.pyright]

include = [
    "gym/**",
    "tests/**"
]

exclude = [
    "**/node_modules",
    "**/__pycache__",

    "gym/envs/box2d/**",
    # "gym/envs/classic_control/**",
    "gym/envs/mujoco/**",
    "gym/envs/toy_text/**",
    "gym/spaces/**",
    "gym/utils/**",
    "gym/vector/**",
    "gym/wrappers/**",
    "tests/**"
]

strict = [

]

typeCheckingMode = "basic"
pythonVersion = "3.7"
typeshedPath = "typeshed"
enableTypeIgnoreComments = true

reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportPrivateUsage = "warning"
reportUntypedFunctionDecorator = "none"
reportMissingTypeStubs = false
reportUnboundVariable = "warning"
reportMissingImports ="error"
reportGeneralTypeIssues ="none"
