---
name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install isort pytest pyupgrade
      - run: isort --diff --check-only --profile black .
      - run: pip install -e .[nomujoco]
      - run: pytest .
      - run: pytest --doctest-modules .
      - run: shopt -s globstar && pyupgrade --py37-plus **/*.py

  pyright:
    name: Check types with pyright
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-platform: ["Linux"]
        python-version: ["3.7"]
      fail-fast: false
    env:
      PYRIGHT_VERSION: 1.1.204
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -e .[nomujoco]
      - uses: jakebailey/pyright-action@v1
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          python-platform: ${{ matrix.python-platform }}
          python-version: ${{ matrix.python-version }}
          no-comments: ${{ matrix.python-version != '3.9' || matrix.python-platform != 'Linux' }}  # Having each job create the same comment is too noisy.
