name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101,B108,B301,B403,B404,B603 .
      - run: black --check .
      - run: codespell --ignore-words-list=nd,reacher,thist,ths -w
      - run: flake8 --ignore=E203,E402,E712,E722,E731,E741,F401,F403,F405,F524,F841,W503
                    --max-complexity=30 --max-line-length=456 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -e .[nomujoco]
      - run: mypy --install-types --non-interactive . || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
