name: test_python
on: [pull_request, push]

jobs:
  test_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker build -f py.Dockerfile \
            --build-arg MUJOCO_KEY=$MUJOCO_KEY \
            --build-arg PYTHON_VER=${{ matrix.python-version }} \
            --tag gym-docker .
      - run: docker run gym-docker pytest --forked
